//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICS.GUI_Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GUILibStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GUILibStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICS.GUI_Library.Properties.GUILibStrings", typeof(GUILibStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        internal static string captException {
            get {
                return ResourceManager.GetString("captException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Error.
        /// </summary>
        internal static string errorBack {
            get {
                return ResourceManager.GetString("errorBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Error.
        /// </summary>
        internal static string errorDB {
            get {
                return ResourceManager.GetString("errorDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment Error.
        /// </summary>
        internal static string errorEnv {
            get {
                return ResourceManager.GetString("errorEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Connection!.
        /// </summary>
        internal static string errorFailedToConnect {
            get {
                return ResourceManager.GetString("errorFailedToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Error.
        /// </summary>
        internal static string errorNext {
            get {
                return ResourceManager.GetString("errorNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        internal static string errorServer {
            get {
                return ResourceManager.GetString("errorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Fetch Error.
        /// </summary>
        internal static string errorSqlFetch {
            get {
                return ResourceManager.GetString("errorSqlFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        internal static string errorStart {
            get {
                return ResourceManager.GetString("errorStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the userid or use Trusted Connection!.
        /// </summary>
        internal static string errorTrusted {
            get {
                return ResourceManager.GetString("errorTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserID Error.
        /// </summary>
        internal static string errorUserID {
            get {
                return ResourceManager.GetString("errorUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the starting point of the wizard!.
        /// </summary>
        internal static string errorWizardStart {
            get {
                return ResourceManager.GetString("errorWizardStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the previous panel!.
        /// </summary>
        internal static string msgBackError {
            get {
                return ResourceManager.GetString("msgBackError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string msgConfirm {
            get {
                return ResourceManager.GetString("msgConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Connection!.
        /// </summary>
        internal static string msgConnected {
            get {
                return ResourceManager.GetString("msgConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Status.
        /// </summary>
        internal static string msgConnectionStatus {
            get {
                return ResourceManager.GetString("msgConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to exit?.
        /// </summary>
        internal static string msgExit {
            get {
                return ResourceManager.GetString("msgExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string msgFinish {
            get {
                return ResourceManager.GetString("msgFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the next panel!.
        /// </summary>
        internal static string msgNextError {
            get {
                return ResourceManager.GetString("msgNextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Database!.
        /// </summary>
        internal static string msgSelectDB {
            get {
                return ResourceManager.GetString("msgSelectDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one Environment..
        /// </summary>
        internal static string msgSelectEnv {
            get {
                return ResourceManager.GetString("msgSelectEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a SQL Server server!.
        /// </summary>
        internal static string msgSelectServer {
            get {
                return ResourceManager.GetString("msgSelectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the database connection in order to load the environments!.
        /// </summary>
        internal static string msgSpecifyDBConn {
            get {
                return ResourceManager.GetString("msgSpecifyDBConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to fetch the SQL Server servers for the following reason:.
        /// </summary>
        internal static string msgSqlFetchError {
            get {
                return ResourceManager.GetString("msgSqlFetchError", resourceCulture);
            }
        }
    }
}
